### ISSUE TITLE
Use parameterized queries

### ISSUE THREAD

**Issue by ianshward** [mapbox/osm-edit-report#10]
To avoid any possibilities of SQL injection, parameterized queries should be used.

- https://github.com/brianc/node-postgres/wiki/FAQ#8-does-node-postgres-handle-sql-injection
- Example https://github.com/brianc/node-postgres/wiki/Client#method-query-parameterized

This should be used anywhere where you're using a variable in a query statement, for example:

- https://github.com/mapbox/report-dt/blob/dev/load.js#L111
- https://github.com/mapbox/report-dt/blob/dev/load.js#L118
- https://github.com/mapbox/report-dt/blob/dev/load.js#L120
- https://github.com/mapbox/report-dt/blob/dev/server.js#L40
- https://github.com/mapbox/report-dt/blob/dev/server.js#L51
- https://github.com/mapbox/report-dt/blob/dev/server.js#L61
- Where else?

**Comment by Rub21** [comment]
@ianshward this task is done: 
https://github.com/mapbox/report-dt/blob/dev/load.js#L69-L70
![screenshot from 2015-02-24 15 40 57](https://cloud.githubusercontent.com/assets/1152236/6358705/942c2d52-bc3b-11e4-8669-90d41b31cb19.png)

https://github.com/mapbox/report-dt/blob/dev/load.js#L119-L123
![screenshot from 2015-02-24 15 42 07](https://cloud.githubusercontent.com/assets/1152236/6358722/b77a2de0-bc3b-11e4-8121-1ea972bf526a.png)


https://github.com/mapbox/report-dt/blob/dev/server.js#L39-L41
![screenshot from 2015-02-24 15 43 32](https://cloud.githubusercontent.com/assets/1152236/6358746/ed0eba3e-bc3b-11e4-89e3-c40a0da2bc29.png)

**Comment by Rub21** [comment]
done, close here.
