### ISSUE TITLE
Rename?

### ISSUE THREAD

**Issue by ianshward** [mapbox/osm-edit-report#11]
It's not clear what report-dt means.  What about osm-user-report or something like that?  cc @lxbarth @Rub21

**Comment by ianshward** [comment]
osm-edit-reports ?

**Comment by Rub21** [comment]
I think is good **osm-edit-reports**

**Comment by ianshward** [comment]
osm-edit-report  (no "s")

**Comment by Rub21** [comment]
I agree using **osm-edit-report** as name

**Comment by Rub21** [comment]
Done: https://www.mapbox.com/osm-edit-report/

Close here
