### ISSUE TITLE
Host data on https

### ISSUE THREAD

**Issue by lxbarth** [mapbox/osm-edit-report#4]
@Rub21 - the app is hosted now under **https**://www.mapbox.com hence it won't be able to pull content from a non-SSL connection. Let's move the server under a Mapbox domain, too.

![](http://dl.dropboxusercontent.com/s/f1jma3nasfrhad1/Screen%20Shot%202015-02-02%20at%204.06.56%20PM.png)

**Comment by Rub21** [comment]
@lxbarth , it was fixed. https://www.mapbox.com/osm-edit-report

**Comment by lxbarth** [comment]
Awesome. Then let's close!

**Comment by lxbarth** [comment]
@Rub21 - never wait for me to close a ticket, always close yourself. Thanks!
