### ISSUE TITLE
Use default value

### ISSUE THREAD

**Issue by lxbarth** [mapbox/osm-edit-report#5]
Problem:

- Right now, when visiting the report for the first time, the page does not show any data

Solution:

- By default, show daily edits for last week

![](http://dl.dropboxusercontent.com/s/1oqvw2qhh8o46j2/Screen%20Shot%202015-02-02%20at%204.10.14%20PM.png)

**Comment by Rub21** [comment]
Done, will be  apply for next release. under mapbox domain.

**Comment by Rub21** [comment]
done close here.
