### ISSUE TITLE
.map files failing to load

### ISSUE THREAD

**Issue by lxbarth** [mapbox/osm-edit-report#6]
There are three .map files that fail to load. Are they actually needed? @Rub21 - please fix or remove them.

![](http://dl.dropboxusercontent.com/s/dyaob17xghuhoft/Screen%20Shot%202015-02-02%20at%204.13.32%20PM.png)

**Comment by Rub21** [comment]
@lxbarth . it was fixed, for next release will work fine.

**Comment by Rub21** [comment]
fixed. close here.
